### ISSUE TITLE
Package pyine is yanked.  Is it necessary?

### ISSUE THREAD

**Issue by thedavidhanks** [Leci37/TensorFlow-stocks-prediction-Machine-learning-RealTime#30]
https://github.com/Leci37/TensorFlow-stocks-prediction-Machine-learning-RealTime/blob/386a580efbb2828dd366b20df2a031d45e5f9252/requirements_x.y.z.txt#L19

I receive the following when trying to install pyine 1.1.2 from requirements_x.y.z.txt
```
ERROR: Ignored the following yanked versions: 1.0.1, 1.1.0, 1.1.1, 1.1.2
ERROR: Could not find a version that satisfies the requirement pyine~=1.1.2 (from versions: none)
ERROR: No matching distribution found for pyine~=1.1.2
```

I haven't yet installed and tested the project yet (though) I see little use of pyine, but if it is required this yanked version can be forced by using the following in the requirements file.
`pyine==1.1.1`

**Comment by Leci37** [comment]
Thank you very much for sharing this bug,
the version number has been corrected.

https://github.com/Leci37/TensorFlow-stocks-prediction-Machine-learning-RealTime/blob/master/requirements.txt
https://github.com/Leci37/TensorFlow-stocks-prediction-Machine-learning-RealTime/blob/master/requirements_x.y.z.txt

Thanks for your time david.

**Comment by thedavidhanks** [comment]
@Leci37 Though, I have not tested, I'm fairly certain this will fail as well.  
the requirement must be specified using "==" not "~="  because the 1.1.1 version was yanked.

Again, pyine is only imported in ./useless/pile_script.py  so I feel that pyine can be omitted from the installed files.
