### ISSUE TITLE
Numpy requirement conflict during pip install.

### ISSUE THREAD

**Issue by thedavidhanks** [Leci37/TensorFlow-stocks-prediction-Machine-learning-RealTime#31]
https://github.com/Leci37/TensorFlow-stocks-prediction-Machine-learning-RealTime/blame/386a580efbb2828dd366b20df2a031d45e5f9252/requirements_x.y.z.txt#L6

When installing with requirements_x.y.z.txt I get the following error.  (numpy cannot satisfy all requirements)
```
ERROR: Cannot install -r requirements_x.y.z.txt (line 2), -r requirements_x.y.z.txt (line 3), -r requirements_x.y.z.txt (line 6) and numpy~=1.21.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy~=1.21.6
    pandas 1.3.5 depends on numpy>=1.17.3; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10"
    numba 0.56.4 depends on numpy<1.24 and >=1.18
    finplot 1.8.4 depends on numpy>=1.22.3
    The user requested numpy~=1.21.6
    pandas 1.3.5 depends on numpy>=1.17.3; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10"
    numba 0.56.4 depends on numpy<1.24 and >=1.18
    finplot 1.8.3 depends on numpy>=1.22.3
    The user requested numpy~=1.21.6
    pandas 1.3.5 depends on numpy>=1.17.3; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10"
    numba 0.56.4 depends on numpy<1.24 and >=1.18
    finplot 1.8.2 depends on numpy>=1.22.3
```

By removing the requirement of 1.8.2, pip installed 1.8.1 successfully.

**Comment by Leci37** [comment]
Thank you very much for sharing this bug, 
the version number has been corrected. 

https://github.com/Leci37/TensorFlow-stocks-prediction-Machine-learning-RealTime/blob/master/requirements.txt
https://github.com/Leci37/TensorFlow-stocks-prediction-Machine-learning-RealTime/blob/master/requirements_x.y.z.txt

thanks for your time
